from ursina import *
from ursina import Ursina, printvar

app = Ursina()
app.setBackgroundColor(0, 0, 0)

texture_earth = ("earth.png")
texture_mars = ("mars.png")
texture_moon = ("moon.png")
texture_mercury = ("mercury.png")
texture_venus = ("venus.png")
texture_jupiter = ("jupiter.png")
texture_saturn = ("saturn.png")
texture_uranus = ("uranus.png")
texture_neptun = ("neptun.png")
texture_sun = ("sun.png")
texture_rings = ("rings.png")
texture_rings2 = ("rings2.png")
texture_io = ("io.jpg")
texture_callisto = ("callisto.png")
texture_titan = ("titan.jpg")
texture_pluto = ("pluto.jpg")
texture_ganymede = ("ganymede.jpg")
texture_enceladus = ("enceladus.jpg")
texture_dione = ("dione.jpg")
texture_rhea = ("rhea.jpg")
texture_tethys = ("tethys.jpg")
texture_ariel = ("ariel.jpg")

sun = Entity(
    model='sphere',
    texture=texture_sun,
    scale=871.3780698,
    double_sided=True,
    visible=False,
    rotation_x=0
)
mercury = Entity(
    model='sphere',
    texture=texture_mercury,
    scale=3.06014424,
    double_sided=True,
    visible=False,
    rotation_x=0
)
venus = Entity(
    model='sphere',
    texture=texture_venus,
    scale=7.591094387,
    double_sided=True,
    visible=False,
    rotation_x=0
)
earth = Entity(
    model='sphere',
    texture=texture_earth,
    scale=8,
    double_sided=True,
    visible=True,
    rotation_x=0
)
moon = Entity(
    model='sphere',
    texture=texture_moon,
    scale=2.179993728,
    double_sided=True,
    visible=False,
    rotation_x=0
)
mars = Entity(
    model='sphere',
    texture=texture_mars,
    scale=4.226904986,
    double_sided=True,
    visible=False,
    rotation_x=0
)
jupiter = Entity(
    model='sphere',
    texture=texture_jupiter,
    scale=87.6889307,
    double_sided=True,
    visible=False,
    rotation_x=0
)
saturn = Entity(
    model='sphere',
    texture=texture_saturn,
    scale=72.86711985,
    double_sided=True,
    visible=False,
    rotation_x=0
)
uranus = Entity(
    model='sphere',
    texture=texture_uranus,
    scale=31.73721258,
    double_sided=True,
    visible=False,
    rotation_x=0
)
neptun = Entity(
    model='sphere',
    texture=texture_neptun,
    scale=30.81119975,
    double_sided=True,
    visible=False,
    rotation_x=0
)
pluto = Entity(
    model='sphere',
    texture=texture_pluto,
    scale=1.4904985888993,
    double_sided=True,
    visible=False,
    rotation_x=0
)
io = Entity(
    model='sphere',
    texture=texture_io,
    scale=2.2848541862652,
    double_sided=True,
    visible=False,
    rotation_x=0
)
callisto = Entity(
    model='sphere',
    texture=texture_callisto,
    scale=3.02326274819692,
    double_sided=True,
    visible=False,
    rotation_x=0
)
titan = Entity(
    model='sphere',
    texture=texture_titan,
    scale=3.2295390404515,
    double_sided=True,
    visible=False,
    rotation_x=0
)
ganymede = Entity(
    model='sphere',
    texture=texture_ganymede,
    scale=3.305111320163,
    double_sided=True,
    visible=False,
    rotation_x=0
)
enceladus = Entity(
    model='sphere',
    texture=texture_enceladus,
    scale=0.3135779241141,
    double_sided=True,
    visible=False,
    rotation_x=0
)
dione = Entity(
    model='sphere',
    texture=texture_dione,
    scale=0.7011602383192,
    double_sided=True,
    visible=False,
    rotation_x=0
)
rhea = Entity(
    model='sphere',
    texture=texture_rhea,
    scale=0.9582941360928,
    double_sided=True,
    visible=False,
    rotation_x=0
)
tethys = Entity(
    model='sphere',
    texture=texture_tethys,
    scale=0.6647851991219,
    double_sided=True,
    visible=False,
    rotation_x=0
)
ariel = Entity(
    model='sphere',
    texture=texture_ariel,
    scale=0.0489191561618,
    double_sided=True,
    visible=False,
    rotation_x=0
)
saturn_rings = Entity(
    model='quad',
    texture=texture_rings,
    double_sided=True,
    scale=156.78896205707,
    rotation_x=87,
    visible=False,
    origin=(0, 0, 0)
)
uranus_rings = Entity(
    model='quad',
    texture=texture_rings2,
    double_sided=True,
    scale=62,
    visible=False,
    origin=(0, 0, 0),
    rotation_x=-170,
    rotation_y=-70
)
text = Text(
    text="Terre",
    origin=(0, -18, -10)
)

Audio(sound_file_name='music.mp3', autoplay=True, loop=True)

def update():
    if held_keys['1']:
        sun.visible = True
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Soleil"
        callisto.visible = False
        pluto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        ariel.visible = False
    elif held_keys['2']:
        sun.visible = False
        mercury.visible = True
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Mercure"
        callisto.visible = False
        pluto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['3']:
        sun.visible = False
        mercury.visible = False
        venus.visible = True
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Venus"
        callisto.visible = False
        enceladus.visible = False
        pluto.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['4']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = True
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Terre"
        callisto.visible = False
        pluto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['5']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = True
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Mars"
        callisto.visible = False
        pluto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['6']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = True
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Jupiter"
        callisto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['7']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = True
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = True
        uranus_rings.visible = False
        io.visible = False
        titan.visible = False
        text.text = "Saturne"
        callisto.visible = False
        pluto.visible = False
        enceladus.visible = False
        ganymede.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['8']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = True
        neptun.visible = False
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = True
        io.visible = False
        titan.visible = False
        text.text = "Uranus"
        callisto.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['9']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = True
        moon.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        text.text = "Neptune"
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['0']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = True
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
        text.text = "Lune"
    elif held_keys['i']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "IO (satellite de Jupiter)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = True
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['c']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Callisto (satellite de Jupiter)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = True
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['t']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Titan (satellite de Saturne)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = True
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['p']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Pluton"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = True
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['g']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Ganymède (satellite de Jupiter)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = True
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['e']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Encelade (satellite de Saturne)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = True
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['d']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Dioné (satellite de Saturne)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = True
        rhea.visible = False
        tethys.visible = False
        ariel.visible = False
    elif held_keys['r']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Rhéa (satellite de Saturne)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = True
        tethys.visible = False
        ariel.visible = False
    elif held_keys['h']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Téthys (satellite de Saturne)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = True
        ariel.visible = False
    elif held_keys['a']:
        sun.visible = False
        mercury.visible = False
        venus.visible = False
        earth.visible = False
        mars.visible = False
        jupiter.visible = False
        saturn.visible = False
        uranus.visible = False
        neptun.visible = False
        moon.visible = False
        text.text = "Ariel (satellite de Neptune)"
        saturn_rings.visible = False
        saturn_rings.visible = False
        uranus_rings.visible = False
        io.visible = False
        callisto.visible = False
        titan.visible = False
        pluto.visible = False
        ganymede.visible = False
        enceladus.visible = False
        dione.visible = False
        rhea.visible = False
        tethys.visible = False
        ariel.visible = True
    earth.rotation_y += 1 * time.dt
    mercury.rotation_y += 1 * time.dt
    venus.rotation_y += 1 * time.dt
    mars.rotation_y += 1 * time.dt
    jupiter.rotation_y += 1 * time.dt
    saturn.rotation_y += 1 * time.dt
    uranus.rotation_y += 1 * time.dt
    neptun.rotation_y += 1 * time.dt
    moon.rotation_y += 1 * time.dt
    pluto.rotation_y += 1 * time.dt
    callisto.rotation_y += 1 * time.dt
    io.rotation_y += 1 * time.dt
    titan.rotation_y += 1 * time.dt
    ganymede.rotation_y += 1 * time.dt
    enceladus.rotation_y += 1 * time.dt
    dione.rotation_y += 1 * time.dt
    rhea.rotation_y += 1 * time.dt
    tethys.rotation_y += 1 * time.dt
    ariel.rotation_y += 1 * time.dt


EditorCamera()

print("\033[92m____________________________________________Interstellar Main Theme by Hans Zimmer____________________________________________\033[0m")
print("\033[92m_____________________________________Simulator developed by Gabriel Dovat (www.galtech.ch)____________________________________\033[0m")

app.run()